apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-default-priority
  labels:
    app: app-default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-default
      tier: web
  template:
    metadata:
      labels:
        app: app-default
        tier: web
    spec:
      containers:
      - name: app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apps-pdb-default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-default