apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-high-priority
  labels:
    app: app-high
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-high
      tier: web
  template:
    metadata:
      labels:
        app: app-high
        tier: web
    spec:
      containers:
      - name: app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 700m
            memory: 700Mi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apps-pdb-high
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-high
